"""Controlled research iteration: evidence-based proposals, approval, stopping rules.

Proposals are generated by transparent rules over the files on disk (run records,
validation status, comparisons, claims, hypotheses). They are suggestions with a
stated rationale; nothing runs until a researcher approves a proposal *and* the
resulting experiment passes the normal preflight (including run approvals).

The ranking score is a documented heuristic, not an optimiser:

    score = 0.4 * relevance + 0.4 * information_gain + 0.2 * feasibility

relevance        1.0 if linked to a research question, else 0.5
information_gain per-rule constant (see RULE_GAIN), reflecting how much the outcome
                 can change a conclusion
feasibility      1.0 if the estimated cost fits the remaining compute budget, scaled
                 down otherwise
"""

from __future__ import annotations

import math
from datetime import datetime, timezone
from typing import Any

from scipy import stats as sps

from . import evidence
from .analysis.stats import describe
from .engine import used_compute_hours
from .experiments import list_runs, list_specs
from .progress import log_decision
from .util import read_json, read_yaml, sha256_obj, utc_now, write_yaml

RULE_GAIN = {"diagnose_failure": 0.9, "resolve_contradiction": 0.95, "replicate": 0.7,
             "increase_sample": 0.75, "baseline": 0.85, "design_experiment": 0.8,
             "ablation": 0.7, "variance_investigation": 0.5, "review_provisional": 0.6,
             "evidence_gap": 0.65}


def _path(project, name="proposals"):
    return project.path("experiments", "plans", f"{name}.yaml")


def load(project) -> list[dict[str, Any]]:
    return (read_yaml(_path(project), {}) or {}).get("proposals", []) or []


def save(project, items) -> None:
    write_yaml(_path(project), {"proposals": items})


def _required_n(effect: float | None, alpha: float, paired: bool, power: float = 0.8) -> int | None:
    if not effect or not math.isfinite(effect) or effect == 0:
        return None
    z = sps.norm.ppf(1 - alpha / 2) + sps.norm.ppf(power)
    n = (z / abs(effect)) ** 2 * (1 if paired else 2)
    return int(math.ceil(n)) + 1


def _proposal(kind, title, based_on, rq, learned, uncertainty, hypothesis, why, changes,
              controlled, outcomes, influence, resources, est_hours, draft_spec=None):
    return {"kind": kind, "title": title, "based_on": based_on, "research_question": rq,
            "learned": learned, "uncertainty": uncertainty, "hypothesis": hypothesis,
            "necessity": why, "variables_changed": changes, "controlled": controlled,
            "possible_outcomes": outcomes, "influence_on_research": influence,
            "resources": resources, "estimated_hours": est_hours, "draft_spec": draft_spec}


def generate(project) -> list[dict[str, Any]]:
    specs = {s["id"]: s for s in list_specs(project)}
    st = project.cfg["statistics"]
    alpha, min_rep = st.get("alpha", 0.05), st.get("min_replicates", 3)
    budget = project.cfg["stopping"].get("compute_budget_hours")
    remaining = (float(budget) - used_compute_hours(project)) if budget is not None else None
    cands: list[dict[str, Any]] = []

    for eid, spec in specs.items():
        runs = list_runs(project, eid)
        rq = (spec.get("research_questions") or [None])[0]
        est1 = float((spec.get("compute") or {}).get("estimated_hours", 0) or 0)
        validated = [r for r in runs if r["validation"]["status"] == "VALIDATED"]
        failed = [r for r in runs if r["status"] in ("FAILED", "TIMED_OUT")]
        prov = [r for r in runs if r["validation"]["status"] == "PROVISIONAL"]
        if failed and not validated:
            cands.append(_proposal(
                "diagnose_failure", f"Diagnose failures of {eid}", [eid], rq,
                f"{len(failed)} run(s) of {eid} failed; none validated.",
                "Whether the failure is a defect in code/config or a property of the method.",
                "The failure has an identifiable, fixable cause.",
                "No evidence can come from this experiment until it runs; repeating blindly wastes compute.",
                ["code or configuration fix (after diagnosis)"], ["dataset", "metrics", "seeds"],
                ["defect found and fixed", "method genuinely fails (a negative result to report)"],
                "Either unblocks the experiment or produces a documented negative finding.",
                "Inspect runs/raw/<run_id>/execution.log; then one re-run.", est1))
        if runs and 0 < len(validated) < min_rep:
            need = min_rep - len(validated)
            used = sorted({r.get("seed") for r in runs if r.get("seed") is not None})
            new_seeds = [s for s in range(max(used + [-1]) + 1, max(used + [-1]) + 1 + need)]
            cands.append(_proposal(
                "replicate", f"Replicate {eid} with {need} more seed(s)", [eid], rq,
                f"{len(validated)} validated run(s); the project minimum is {min_rep}.",
                "Run-to-run variability is unknown, so no interval or test is meaningful.",
                "Results are stable across seeds.", "Required before any inferential claim.",
                ["seed"], ["all other configuration (identical config hash)"],
                ["low variance (supports stability)", "high variance (weakens conclusions)"],
                "Determines whether comparisons involving this experiment can be tested.",
                f"{need} run(s) x {est1} h", need * est1,
                {"action": "run", "experiment": eid, "seeds": new_seeds}))
        if prov:
            cands.append(_proposal(
                "review_provisional", f"Review {len(prov)} provisional run(s) of {eid}", [eid], rq,
                "Some runs passed checks only provisionally.",
                "; ".join(sorted({i['message'] for r in prov for i in r['validation']['issues']
                                  if i['severity'] == 'PROVISIONAL'}))[:400],
                "n/a (review task)", "Provisional runs cannot support verified claims.",
                [], [], ["issues resolved and re-run", "runs excluded with a documented reason"],
                "Decides whether these runs can count as evidence.", "researcher time only", 0.0))
        if spec.get("type") == "proposed":
            has_base = any(specs.get(c, {}).get("type") == "baseline" for c in spec.get("compare_with", []))
            if not has_base:
                cands.append(_proposal(
                    "baseline", f"Add a baseline comparison for {eid}", [eid], rq,
                    f"{eid} is a proposed method with no baseline in compare_with.",
                    "Performance of the proposed method has no reference point.",
                    "The proposed method differs from an established baseline.",
                    "Any claim of improvement requires a fair, documented comparison.",
                    ["method (baseline instead of proposed)"],
                    ["dataset, splits, metrics, seeds, preprocessing"],
                    ["proposed better", "no difference", "baseline better"],
                    "Determines whether a contribution claim is possible at all.",
                    "same as the proposed experiment", est1 * max(1, len(spec.get("seeds") or [1]))))
            has_abl = any(s.get("type") == "ablation" and eid in (s.get("depends_on", []) + s.get("compare_with", []))
                          for s in specs.values())
            if validated and not has_abl:
                cands.append(_proposal(
                    "ablation", f"Ablate the components of {eid}", [eid], rq,
                    f"{eid} has validated results but no ablation.",
                    "Which component is responsible for the observed behaviour.",
                    "Removing a component changes the metric.",
                    "Attribution claims need ablations that isolate one variable at a time.",
                    ["one component at a time"], ["everything else"],
                    ["a component matters", "components are redundant"],
                    "Supports or removes mechanism claims.", "one run set per component", est1))
        conf = st.get("confidence_level", 0.95)
        for name in [m["name"] for m in spec.get("metrics", [])]:
            vals = [r["metrics"][name] for r in validated if isinstance((r.get("metrics") or {}).get(name), (int, float))]
            d = describe(vals, conf)
            if d.get("cv") is not None and d["cv"] > 0.2 and d["n"] >= 3:
                cands.append(_proposal(
                    "variance_investigation", f"Investigate variance of {name} in {eid}", [eid], rq,
                    f"{name} has a coefficient of variation of {d['cv']:.2f} across {d['n']} runs.",
                    "Whether the variance comes from seeds, data order, or instability of the method.",
                    "Variance is driven by an identifiable factor.",
                    "High variance can hide or fake differences between conditions.",
                    ["source of randomness, one at a time"], ["configuration"],
                    ["variance explained", "method intrinsically unstable (report as limitation)"],
                    "Sets how much confidence comparisons deserve.", "a few extra runs", est1 * 3))

    # inconclusive comparisons
    for p in sorted(project.path("analysis", "comparisons").glob("*.json")):
        s = read_json(p) or {}
        for c in s.get("comparisons", []):
            r = c["result"]
            if r.get("p_value") is None or not r.get("significant_after_adjustment"):
                es = (r.get("effect_size") or {}).get("value")
                need = _required_n(es, alpha, r.get("paired", False))
                ref = s["reference"]["experiment"]
                cands.append(_proposal(
                    "increase_sample", f"Resolve inconclusive {ref} vs {c['other']} on {s['metric']}",
                    [ref, c["other"]], (specs.get(ref, {}).get("research_questions") or [None])[0],
                    f"Comparison is inconclusive (p={r.get('p_value')}, adjusted={r.get('p_adjusted')}, "
                    f"n={r['n_a']}/{r['n_b']}).",
                    "Whether a real difference exists at a practically relevant size.",
                    "The two conditions differ on the metric.",
                    "An inconclusive result must not be reported as 'no difference' or as an improvement.",
                    ["number of replicates"], ["all configuration"],
                    ["difference detected", "difference remains undetectable at the stated power"],
                    "Turns an inconclusive comparison into a supported positive or negative finding.",
                    (f"rough power estimate: ~{need} replicates per group for 80% power at the observed "
                     f"effect size {es:.3g} (normal approximation; treat as indicative)") if need else
                    "effect size unavailable; collect at least the project minimum of replicates",
                    None))

    # claims problems
    for c in evidence.load(project):
        if c.get("contradicted_by"):
            cands.append(_proposal(
                "resolve_contradiction", f"Resolve contradiction between {c['id']} and {', '.join(c['contradicted_by'])}",
                c.get("experiments", []), c.get("research_question"),
                "Two claims cite the same source with different values.",
                "Which value is correct, and why they diverge.", "n/a (investigation)",
                "Conflicting evidence must be investigated, never silently resolved.",
                [], [], ["one claim corrected/superseded", "a real discrepancy to report"],
                "Protects the manuscript from contradictory statements.", "researcher time", 0.0))

    # hypotheses / RQs without experiments
    linked_h = {h for s in specs.values() for h in s.get("hypotheses", [])}
    for h in project.cfg["research"]["hypotheses"]:
        if h["id"] not in linked_h and "RESEARCHER INPUT" not in h.get("statement", ""):
            cands.append(_proposal(
                "design_experiment", f"Design an experiment testing {h['id']}", [], h.get("rq"),
                f"Hypothesis {h['id']} is not tested by any experiment.", h["statement"], h["statement"],
                "An untested hypothesis cannot be supported or refuted.",
                ["to be designed"], ["to be designed"], ["supported", "refuted", "inconclusive"],
                "Directly addresses a stated hypothesis.", "to be estimated", None))
    linked_rq = {q for s in specs.values() for q in s.get("research_questions", [])}
    for q in project.cfg["research"]["questions"]:
        if q["id"] not in linked_rq and "RESEARCHER INPUT" not in q["text"]:
            cands.append(_proposal(
                "evidence_gap", f"No experiment addresses {q['id']}", [], q["id"],
                f"{q['id']} has no linked experiment.", q["text"], "to be formulated",
                "Every research question needs evidence or an explicit scope decision.",
                [], [], ["experiment designed", "question descoped (record a decision)"],
                "Closes or explicitly scopes an open question.", "to be estimated", None))

    # dedupe against existing proposals with the same signature and unchanged evidence
    existing = load(project)
    seen = {(p["signature"], p["evidence_hash"]) for p in existing}
    new = []
    n0 = len(existing)
    for cand in cands:
        sig = sha256_obj([cand["kind"], cand["based_on"], cand["title"]])[:16]
        ev = sha256_obj([cand["learned"], cand["uncertainty"]])[:16]
        if (sig, ev) in seen:
            continue
        seen.add((sig, ev))
        rel = 1.0 if cand["research_question"] else 0.5
        est = cand["estimated_hours"]
        if est is None or remaining is None:
            feas = 0.7 if est is None else 1.0
        elif est <= 0:
            feas = 1.0
        else:
            feas = max(0.0, min(1.0, remaining / est)) if remaining > 0 else 0.0
        score = round(0.4 * rel + 0.4 * RULE_GAIN[cand["kind"]] + 0.2 * feas, 3)
        new.append({"id": f"P-{n0 + len(new) + 1:03d}", "status": "proposed", "created_at": utc_now(),
                    "signature": sig, "evidence_hash": ev,
                    "ranking": {"score": score, "relevance": rel, "information_gain": RULE_GAIN[cand["kind"]],
                                "feasibility": round(feas, 3)}, **cand})
    save(project, existing + new)
    return sorted(new, key=lambda p: -p["ranking"]["score"])


def decide(project, pid: str, approve: bool, by: str, note: str = "") -> dict[str, Any]:
    if not by.strip():
        raise ValueError("a decision must name the researcher (--by)")
    items = load(project)
    p = next((x for x in items if x["id"] == pid), None)
    if p is None:
        raise KeyError(f"proposal {pid} not found")
    if p["status"] != "proposed":
        raise ValueError(f"proposal {pid} is already {p['status']}")
    p.update(status="approved" if approve else "rejected", decided_by=by, decided_at=utc_now(),
             decision_note=note)
    save(project, items)
    log_decision(project, title=f"{'Approved' if approve else 'Rejected'} proposal {pid}: {p['title']}",
                 motivation=p["necessity"], evidence=p["learned"],
                 alternatives="approve / reject / defer", consequences=p["influence_on_research"],
                 by=by, kind="proposal", note=note)
    return p


# ------------------------------------------------------------------ loop and stopping

def iterations(project) -> list[dict[str, Any]]:
    return (read_yaml(_path(project, "iterations"), {}) or {}).get("iterations", []) or []


def _save_iterations(project, items) -> None:
    write_yaml(_path(project, "iterations"), {"iterations": items})


def stopping_status(project) -> dict[str, Any]:
    s = project.cfg["stopping"]
    its = iterations(project)
    used = used_compute_hours(project)
    reasons_stop, reasons_review, info = [], [], []
    if s.get("max_iterations") and len(its) >= s["max_iterations"]:
        reasons_stop.append(f"max_iterations reached ({len(its)}/{s['max_iterations']})")
    if s.get("compute_budget_hours") is not None and used >= float(s["compute_budget_hours"]):
        reasons_stop.append(f"compute budget exhausted ({used:.2f}/{s['compute_budget_hours']} h)")
    if s.get("deadline"):
        try:
            dl = datetime.fromisoformat(str(s["deadline"]))
            if dl.tzinfo is None:
                dl = dl.replace(tzinfo=timezone.utc)
            if datetime.now(timezone.utc) >= dl:
                reasons_stop.append(f"deadline {s['deadline']} passed")
        except ValueError:
            info.append(f"deadline {s['deadline']!r} is not ISO formatted; ignored")
    w = s.get("saturation_window")
    closed = [i for i in its if i.get("closed_at")]
    if w and len(closed) >= w and all(i.get("new_verified_claims", 0) == 0 for i in closed[-w:]):
        reasons_stop.append(f"saturation: no new verified claims in the last {w} iteration(s)")
    every = s.get("require_review_every", 1)
    since = 0
    for i in reversed(its):
        if i.get("reviewed_by"):
            break
        if i.get("closed_at"):
            since += 1
    if since >= every:
        reasons_review.append(f"{since} closed iteration(s) since the last researcher review "
                              f"(required every {every}): run `research loop review --by NAME`")
    hyps = project.cfg["research"]["hypotheses"]
    open_h = [h["id"] for h in hyps if h.get("status", "proposed") == "proposed"]
    claims = evidence.load(project)
    rq_ok = {c.get("research_question") for c in claims if c["status"] == "verified"}
    open_rq = [q["id"] for q in project.cfg["research"]["questions"] if q["id"] not in rq_ok]
    if not open_h and not open_rq:
        info.append("minimum evidence met: every hypothesis has a verdict and every RQ a verified claim")
    return {"iterations": len(its), "compute_used_hours": round(used, 4),
            "must_stop": reasons_stop, "review_required": reasons_review, "info": info,
            "open_hypotheses": open_h, "rqs_without_verified_claims": open_rq,
            "may_continue": not reasons_stop and not reasons_review}


def start_iteration(project, by: str) -> dict[str, Any]:
    st = stopping_status(project)
    if not st["may_continue"]:
        raise ValueError("cannot start an iteration: " + "; ".join(st["must_stop"] + st["review_required"]))
    approved = [p["id"] for p in load(project) if p["status"] == "approved" and not p.get("iteration")]
    if not approved:
        raise ValueError("no approved, unscheduled proposals; approve one with `research proposals approve`")
    its = iterations(project)
    verified0 = sum(1 for c in evidence.load(project) if c["status"] == "verified")
    it = {"n": len(its) + 1, "started_at": utc_now(), "started_by": by, "proposals": approved,
          "verified_claims_at_start": verified0, "closed_at": None}
    items = load(project)
    for p in items:
        if p["id"] in approved:
            p["iteration"] = it["n"]
    save(project, items)
    _save_iterations(project, its + [it])
    return it


def close_iteration(project, summary: str = "") -> dict[str, Any]:
    its = iterations(project)
    if not its or its[-1].get("closed_at"):
        raise ValueError("no open iteration")
    verified = sum(1 for c in evidence.load(project) if c["status"] == "verified")
    its[-1].update(closed_at=utc_now(), summary=summary,
                   new_verified_claims=verified - its[-1].get("verified_claims_at_start", 0))
    _save_iterations(project, its)
    return its[-1]


def review(project, by: str, note: str = "") -> None:
    its = iterations(project)
    if not its:
        raise ValueError("no iterations to review")
    its[-1]["reviewed_by"] = by
    its[-1]["reviewed_at"] = utc_now()
    its[-1]["review_note"] = note
    _save_iterations(project, its)
    log_decision(project, title=f"Researcher review after iteration {its[-1]['n']}", motivation="review checkpoint",
                 evidence=note or "see progress report", alternatives="continue / stop / change direction",
                 consequences="iteration loop may continue", by=by, kind="review")
